import { 
  QuestionEvaluation, 
  OverallEvaluation, 
  TechnicalEvaluation, 
  CommunicationEvaluation, 
  BehaviorEvaluation 
} from "../../types/interviewReport";

export const calculateScores = (
  evaluations: QuestionEvaluation[]
): {
  overallEvaluation: OverallEvaluation;
  technicalEvaluation: TechnicalEvaluation;
  communicationEvaluation: CommunicationEvaluation;
  behavioralEvaluation: BehaviorEvaluation;
} => {
  if (evaluations.length === 0) {
    throw new Error("Cannot score an empty interview");
  }

  const numQuestions = evaluations.length;

  // Averages across all questions
  const avgTechnicalDepth = evaluations.reduce((acc, curr) => acc + curr.technicalDepth, 0) / numQuestions;
  const avgCorrectness = evaluations.reduce((acc, curr) => acc + curr.correctness, 0) / numQuestions;
  const avgCompleteness = evaluations.reduce((acc, curr) => acc + curr.completeness, 0) / numQuestions;
  const avgClarity = evaluations.reduce((acc, curr) => acc + curr.clarity, 0) / numQuestions;
  const avgConfidence = evaluations.reduce((acc, curr) => acc + curr.confidence, 0) / numQuestions;

  // Category Scores
  const technicalScore = Math.round((avgTechnicalDepth * 0.4) + (avgCorrectness * 0.4) + (avgCompleteness * 0.2));
  const communicationScore = Math.round(avgClarity);
  const behavioralScore = Math.round((avgConfidence + avgClarity) / 2); // Simplified without dedicated behavioral metrics yet
  const problemSolvingScore = Math.round((avgCorrectness + avgCompleteness) / 2);
  const confidenceScore = Math.round(avgConfidence);
  
  // Time Management: Ideal answer duration is roughly 2-4 minutes.
  // Penalize for very short (<30s) or very long (>6m) answers
  const timeScores = evaluations.map(ev => {
    const mins = ev.durationMs / 60000;
    if (mins >= 1.5 && mins <= 4.5) return 100;
    if (mins > 4.5 && mins <= 6) return 80;
    if (mins > 6) return 50;
    if (mins >= 0.5 && mins < 1.5) return 70;
    return 40; // less than 30s
  });
  const timeManagementScore = Math.round(timeScores.reduce((acc, curr) => acc + curr, 0) / numQuestions);

  // Overall Score (Weighted)
  const overallScore = Math.round(
    (technicalScore * 0.40) +
    (communicationScore * 0.20) +
    (problemSolvingScore * 0.15) +
    (behavioralScore * 0.10) +
    (confidenceScore * 0.10) +
    (timeManagementScore * 0.05)
  );

  return {
    overallEvaluation: {
      overallScore,
      technicalScore,
      communicationScore,
      confidenceScore,
      behavioralScore,
      problemSolvingScore,
      timeManagementScore,
      summary: "A comprehensive summary will be generated by AI."
    },
    technicalEvaluation: {
      score: technicalScore,
      strengths: [], // Populated by analysis service
      weaknesses: []
    },
    communicationEvaluation: {
      score: communicationScore,
      clarity: avgClarity >= 80 ? "Excellent" : avgClarity >= 60 ? "Good" : "Needs Improvement",
      conciseness: timeManagementScore >= 80 ? "Excellent" : timeManagementScore >= 60 ? "Good" : "Needs Improvement",
    },
    behavioralEvaluation: {
      score: behavioralScore,
      leadership: "N/A", // Populated by specific questions
      collaboration: "N/A"
    }
  };
};
